### ISSUE TITLE
Fix @electron/asar import, a sub-dependency of @mapeo/core

### ISSUE THREAD

**Issue by EvanHahn** [digidem/CoMapeo-mobile#204]
`@mapeo/core@9.0.0-alpha.5` imports `@electron/asar`, which [has the following line][0]:

```javascript
const fs = process.versions.electron ? require('original-fs') : require('fs')
```

For some reason, this gets bundled to:

```javascript
// ...fake bundled code...
const originalFs = require('original-fs')
// ...fake bundled code...
```

This causes a crash on app startup because we can't import `original-fs`.

We should fix this somehow.

[0]: https://github.com/electron/asar/blob/d50b03f48ce60383a62cf322d7868bc2a183a41e/lib/wrapped-fs.js#L3

**Comment by achou11** [comment]
think this is a limitation of rollup (or, most bundlers?). probably tries to not be too smart about the fact that it's technically conditionally required and just flattens the requires, which causes things to break for us.

think the simplest solution would be to add a patch to update that line so that it's only requiring from `fs`
