### ISSUE TITLE
Adopt Expo Prebuild

### ISSUE THREAD

**Issue by ErikSin** [digidem/comapeo-mobile#225]
Switch from a RN bare work flow to [Continuous Native Generation](https://docs.expo.dev/workflow/continuous-native-generation/) (see [Adopt Prebuild](https://docs.expo.dev/guides/adopting-prebuild/)).

To Do:
- [x] Determine any modifications made to native code (can create a new bare react native project and compare android folders for diffs)
- [x] For any modification made, determine dependencies required the native code changes.
- [x] Determine if there are expo alternatives for these libraries OR if we should create an [Expo Plugin](https://docs.expo.dev/config-plugins/plugins-and-mods/). If there is an alternative library that can be used consult @achou11 or @ErikSin to determine if we should switch libraries
- [x] [Follow Expo instruction to set up app.config.js](https://docs.expo.dev/build-reference/variants/#using-production-variant) to configure the [development, preview, and production builds](https://docs.expo.dev/build/eas-json/#common-use-cases). For now the build configurations will be the same, but create the 3 categories in the app config for later configuration
- [x] Figure out the work needed to get [nodejs-mobile-react-native](https://nodejs-mobile.github.io/) working with Expo
    - based on the [documented installation instructions](https://nodejs-mobile.github.io/docs/guide/guide-react-native/getting-started), there maybe be some additional work needed so that the nodejs-assets/ directory is placed into the correct place in the generated android/ directory.

**Comment by gmaclennan** [comment]
Expo now calls this ["Continuous Native Integration"](https://docs.expo.dev/workflow/continuous-native-generation/), although they also call this ["Adopt Prebuild"](https://docs.expo.dev/guides/adopting-prebuild/).

In terms of nodejs-mobile-react-native, I have successfully run this in an expo project with CNG (I just set up the expo project and followed the nodejs-mobile setup instructions - it all works with auto-linking). I think we have some patches for prebuilds, so we might need some work to integrate those.

Can we add a follow-up task to this to use setup a CI workflow for [generating development builds with `expo-dev-client`](https://docs.expo.dev/develop/development-builds/introduction/) whenever the native code changes, and dev instructions so that devs can work on the react-native side of code without needing to install Android SDK or XCode on their laptop?

**Comment by gmaclennan** [comment]
We also want 3 variants set up, each with a separate app id and different coloured app icons:

- production builds
- testing builds (non-public, shared with team and trusted users for testing release candidates and previewing new features)
- development builds (debug turned on, used by developers while building the app)

Keeping these as separate variants allows us avoid breaking existing data in production versions, since all data is local stored in the app.

**Comment by CDFN** [comment]
For this point:
> Determine if there are expo alternatives for these libraries OR if we should create an [Expo Plugin](https://docs.expo.dev/config-plugins/plugins-and-mods/). If there is an alternative library that can be used consult @achou11 or @ErikSin to determine if we should switch libraries

the only library containing native code is currently mapbox which isn't possible to replace with any expo library so it has to 
stay.

There are other libraries that could be replaced with expo alternatives such as:
`react-native-bootsplash` -> https://docs.expo.dev/versions/latest/sdk/splash-screen/ (will create another PR for this)
`react-native-device-info` -> https://docs.expo.dev/versions/latest/sdk/device/ (will create another PR for this)
`react-native-android-open-settings` -> https://docs.expo.dev/versions/latest/sdk/linking/ (will create another PR for this)
`react-native-indicators` -> https://reactnative.dev/docs/activityindicator (let us know if you want to switch as design would change when migrating)
`react-native-vector-icons` -> https://docs.expo.dev/guides/icons/ (let us know if you want to switch, no tradeoffs and no design changes required)

**Comment by bohdanprog** [comment]
Here is [PR](https://github.com/digidem/comapeo-mobile/pull/301) moving from react-native-bootsplash to  Expo SplashScreen 
Closes #301
