### ISSUE TITLE
Use Expo App Services for CI Phase 1

### ISSUE THREAD

**Issue by ErikSin** [digidem/comapeo-mobile#226]
Configure project to be built of Expo App Services.

## To Do:
- [x] Follow set up [instructions](https://docs.expo.dev/build/setup/). 
- [x] Allow for builds of [APK's for internal use](https://docs.expo.dev/build-reference/apk/)
- [x] Add [Sentry Auth Token](#224 ) as a [secret](https://docs.expo.dev/build-reference/variables/#using-secrets-in-environment-variables)

**Comment by gmaclennan** [comment]
A few details to add to this task:

- set up a signing key - we will replace it with our own key later, but can set up the integration for now. 
- we also distribute production apks outside the App Store
- the apk should include both arm32 and arm64 architectures, because users don't know which one to download if we have separate archs. x86 and x64 is rare enough that it's not necessary for apk builds.
- would be good to integrate EAS with GitHub and figure out how we trigger builds. 

The stretch goal of this task is to set up publishing to Google play and distribution of QA versions for internal testing. Also uploads of releases to S3 for users who don't use the play store and just want to download an apk. Also would be good to look at work needed to get expo updates working.
