### ISSUE TITLE
Fix Navigation from Details Screen

### ISSUE THREAD

**Issue by ErikSin** [digidem/comapeo-mobile#515]
The navigation from the details screen is unpredictable. As seen in [this issue](https://www.notion.so/digidem/f551401ee13f4652b3b3f23e52db9783?v=c58a7b022e084c2bae2c4379bf0c67e7&p=48f182ae20884e81985dff81581833fe&pm=s), pressing "done" navigates the user back to the ma, but I was unable to reproduce the error on my device

## To Do
- [ ] Determine and fix error

## Notion Issue
https://www.notion.so/digidem/f551401ee13f4652b3b3f23e52db9783?v=c58a7b022e084c2bae2c4379bf0c67e7&p=48f182ae20884e81985dff81581833fe&pm=s

**Comment by achou11** [comment]
i believe the error is caused by this:

https://github.com/digidem/comapeo-mobile/blob/c2dcc5f98d3b36fce51dadb380309fa9d6996443/src/frontend/screens/ObservationFields/index.tsx#L99

this screen can be navigated to by both the observation creation and observation editing flows. It's erroneously assuming that it's always coming from the latter. If you're doing the former, attempting to navigate to a non-existent screen in the stack probably triggers some fallback mechanism in react-navigation to navigate to the default screen, which is usually the map

**Comment by achou11** [comment]
> i believe the error is caused by these:
> 
> https://github.com/digidem/comapeo-mobile/blob/c2dcc5f98d3b36fce51dadb380309fa9d6996443/src/frontend/screens/ObservationFields/index.tsx#L46
> 
> https://github.com/digidem/comapeo-mobile/blob/c2dcc5f98d3b36fce51dadb380309fa9d6996443/src/frontend/screens/ObservationFields/index.tsx#L99
> 
> this screen can be navigated to by both the observation creation and observation editing flows. They're erroneously assuming that it's always coming from the latter. If you're doing the creation flow, attempting to navigate to a non-existent screen in the stack probably triggers some fallback mechanism in react navigation to navigate to the default screen, which is usually the map

see explanation that disproves this here: https://github.com/digidem/comapeo-mobile/pull/540#issuecomment-2248780448
